### ISSUE TITLE
Add smooth scrolling to hash links

### ISSUE THREAD

**Issue by 2ndTwo** [2ndTwo/_s#43]
This helps people understand that they're moving from one place on the page to another.

Add this to the relevant `/base` file:

```scss
html {
  scroll-behavior: smooth;
  
  @media (prefers-reduced-motion: reduce) {
    scroll-behavior: auto;
  }
}
```
