### ISSUE TITLE
Add Sass mixin for variable fonts

### ISSUE THREAD

**Issue by 2ndTwo** [2ndTwo/_s#48]
The mixin should output something like this: 

```scss
.element {
  font-family: 'Markazi Text';
  font-weight: 400;
}

@supports (font-variation-settings: "wght" 450) {
  .element {
    font-family: 'Markazi Text';
    font-weight: 450;
  }
}
```

See [this link](https://developers.google.com/fonts/docs/css2#legacy_browser_support) from Google Fonts.
