### ISSUE TITLE
Improve default look of site when user has inverted colors

### ISSUE THREAD

**Issue by 2ndTwo** [2ndTwo/_s#49]
The code should look something like this:

```scss
@media (inverted-colors) {
  img { filter: invert(1); }
  * { box-shadow: none !important; text-shadow: none !important; }
}
```

It should go in the `base/_media.scss` file
